# Generated by Django 5.1.7 on 2025-03-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medidores', '0002_delete_consumomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoModel',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('consumo_kwh', models.FloatField()),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True)),
                ('numero_serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medidores.medidormodel')),
            ],
        ),
    ]
