# Generated by Django 5.1.7 on 2025-03-22 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidorModel',
            fields=[
                ('numero_serie', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuariomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoModel',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('consumo_kwh', models.FloatField()),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True)),
                ('numero_serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medidores.medidormodel')),
            ],
        ),
    ]
